import "./globals.css";
import type { Metadata } from "next";
import NextUIProvider from "./context/NextUIProvider";
import AuthProvider from "./context/AuthProvider";

import NavBar from "./components/NavBar/NavBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="min-w-screen">
        <NextUIProvider>
          <AuthProvider>
            {/* <NavBar /> */}
            <main className="min-w-screen">{children}</main>
          </AuthProvider>
        </NextUIProvider>
      </body>
    </html>
  );
}
